### ISSUE TITLE
A typo in the "Why I Care" Chapter

### ISSUE THREAD

**Issue by larsonkarl** [dilgerma/eventsourcing-book#10]
In the ePub 24-11-15 version, in the "Why I Care" Chapter page 10, a typo: 

Assume "communicate.successful" should be "communicate successfully"

“We found that the root of many issues wasn’t premature optimization, as many developers think. It was the lack of a common language—the lack of a structured way to communicate.successful”

**Comment by dilgerma** [comment]
thanks! fixed in the next release
