### ISSUE TITLE
Typo in the ePub 24-11-15 version, in the "Why I Care" Chapter:

### ISSUE THREAD

**Issue by larsonkarl** [dilgerma/eventsourcing-book#11]
In the ePub 24-11-15 version, in the "Why I Care" Chapter:

Text: “It’s developers understanding, not your business knowledge that becomes software.”

Issue: Missing a ' after "developers as in:

Corrected: “It’s developers' understanding, not your business knowledge that becomes software.”

Better: “It’s the developers' understanding, not your business knowledge that becomes software.”

So minor, but you have it correct in later use of the quote so thought I'd mention it.

**Comment by dilgerma** [comment]
thanks! appreciate the help a lot!
