### ISSUE TITLE
PDF and Epub version 2024-11-15

### ISSUE THREAD

**Issue by ralmlopez** [dilgerma/eventsourcing-book#12]
Chapter 8, Pdf page 134 (also in EPUB), 4th paragraph, last sentence: "concicous decicion" should be "conscious decision"

Chapter 10, Pdf page 170 (also in EPUB), 2nd paragraph, last sentence: "Even if a slice is completely deleted and rebuild from scratch will these tests typically just continue to work." should be "Even if a slice is completely deleted and rebuilt from scratch, these tests will typically continue to work."

**Comment by dilgerma** [comment]
Thanks! will be in the next release of the book!
Really appreciate the help

Regards

Martin
