### ISSUE TITLE
Typo in "What are Projections?" Chapter

### ISSUE THREAD

**Issue by jakobt** [dilgerma/eventsourcing-book#13]
Specific is spelled as specficic

Pagenumber 18 (Page 40 in PDF)

I Foundations -> Event Sourcing - what is it -> What are Projections?

> Projections allow us to use the events stored in event-streams
> to build specific views of our information for different use cases.
> A projection takes all events from one or more event streams
> and builds a **specficic** view

**Comment by dilgerma** [comment]
thanks a lot, fixed in the next release
