### ISSUE TITLE
Typo in "Event Sourcing - what is it?" section, page 44 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#15]
"In `germany` we say “probieren geht über studieren” which translates to “don ́t just read about it, do it.”"

Correction:
"In `Germany` we say “probieren geht über studieren” which translates to “don ́t just read about it, do it.”"

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
