### ISSUE TITLE
Suggestion for "Event Sourcing - what is it?" section, pages 57-58 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#16]
"Event streaming is often much more technical, and the events are much more fine-grained `typically` than in Event Sourcing."

Suggestion for better clarity:
"Event streaming is often much more technical, and the events are `typically` much more fine-grained than in Event Sourcing."

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
