### ISSUE TITLE
Suggestion for "Event Sourcing - what is it?" section, page 58 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#17]
"In Event Streaming`,` this is not practical, as the number of events is simply too high to do this efficiently `typically`."

Suggestion for better clarity:
"In Event Streaming this is not practical, as `typically` the number of events is simply too high to do this efficiently."

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
