### ISSUE TITLE
Typo in "Event Sourcing - what is it?" section, page 59 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#18]
"This is the last of the most common misconceptions and myths we’ll try to debunk in this chapter. And this is a `real common` one."

Correction suggestion:
"This is the last of the most common misconceptions and myths we’ll try to debunk in this chapter. And `this one is really common`."

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
