### ISSUE TITLE
Grammar suggestion for "Event Sourcing - what is it?" section, page 61 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#20]
"the important aspect is not the technology itself but the mindset `how` to handle data."

Suggestion:
"the important aspect is not the technology itself but the mindset `for how` to handle data."

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thank you! these nuances are hard for a non-native speaker
