### ISSUE TITLE
Typo in "Planning Systems using Event Modeling" section, page 66 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#21]
"`Its` a great tool even today"

Correction suggestion:
"`It's` a great tool even today"

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks! I´m really thankful for these advices. It ´s so hard to catch them all

**Comment by gimelg** [comment]
It's my pleasure! I'm really enjoying the book so far, and really looking forward to the implementation sections. There aren't nearly enough in-depth resources for Event Sourcing, so I was thrilled to find this.
