### ISSUE TITLE
Typo in "Internal versus external data" section, page 115 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#25]
"There is a whole book written about the subject of versioning in event-sourced systems by Greg Young that goes into great detail about the cases you need to `address`<sup>16</sup>"

Correction (missing period):
"There is a whole book written about the subject of versioning in event-sourced systems by Greg Young that goes into great detail about the cases you need to `address.`<sup>16</sup>"

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
