### ISSUE TITLE
Typo in "The Anatomy of an event-sourced Application" section, page 126 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#26]
"We’ll talk about aggregates in a minute`, its` more or less the component that makes crucial decisions in our system."

Correction suggestion (missing apostrophe, and also a semicolon is better suited here instead of a comma):
"We’ll talk about aggregates in a minute`; it's` more or less the component that makes crucial decisions in our system."

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
