### ISSUE TITLE
Typo in "The Anatomy of an event-sourced Application" section, page 128 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#28]
I encourage you to search for the term “Dynamic Consistency `Boundary`”<sup>17</sup>

Correction suggestion (missing period):
I encourage you to search for the term “Dynamic Consistency `Boundary.`”<sup>17</sup>

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
