### ISSUE TITLE
Wrong words in diagrams

### ISSUE THREAD

**Issue by fitims** [dilgerma/eventsourcing-book#3]
page 52 - Fig 3.6 Blue box should say command, it says event
page 54 - Fig 3.8 green box says events, it should say read models
page 68 - Fig 3.16 - everything says events it show be commands, and read models also

**Comment by AndreKraemer** [comment]
I want to add Fig 4.4 on page 85. In version 2 the name column should contain the value Andreas instead of Markus

**Comment by dilgerma** [comment]
thanks! fixed all but 4.4 - that´s by intention. "Andreas" was not stored. I made that clearer in the  text.
