### ISSUE TITLE
Grammar suggestion in "Event Streaming , Event Sourcing and Stream Design" section, page 142 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#31]
There could also be System C that subscribes to the “user positions” topic `but is only interested in` reporting purposes

Correction suggestion:
There could also be System C that subscribes to the “user positions” topic, `but it's only interested in it for` reporting purposes

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
