### ISSUE TITLE
Suggestion for "Domain Driven Design" section, page 153 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#35]
We discuss and meet every two weeks in refinements to discuss these requirements, most of the time without `discussing the the` business stakeholders directly.

The typo was already addressed [here](https://github.com/dilgerma/eventsourcing-book/issues/34), but I thought maybe the word `discussing` can be replaced with `involving` for better clarity and readability (too many 'discussing'):
We discuss and meet every two weeks in refinements to discuss these requirements, most of the time without `involving` the business stakeholders directly.

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks! much better!
