### ISSUE TITLE
Suggestion for "Handling transactions in distributed systems using Sagas" section, page 174 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#37]
Don ́t get me wrong, I ́m not judging this `approach`. There are `very valid` situations, where orchestrating a process is a `valid approach`.

Suggestion for readability and removing repetition:
Don ́t get me wrong, I ́m not judging this approach. There are `situations` for which orchestrating a process is a `perfectly valid solution`.

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
