### ISSUE TITLE
Grammar suggestion in "Handling transactions in distributed systems using Sagas" section, page 176 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#38]
Now as we all know, there is no free lunch. Debugging these decoupled workflows and finding problems is much more com- plicated than `having the central process manager instance. So if you need to decide between one of these approaches, it always requires careful analysis and some experience to make the right decisions.`

Suggestion for grammar and readability:
Now as we all know, there is no free lunch. Debugging these decoupled workflows and finding problems is much more com- plicated than `in a central process manager instance. Therefore, deciding between one of these approaches always requires careful analysis, and some experience, in order to make the right call.`

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks! much better
