### ISSUE TITLE
Grammar suggestion in "Handling transactions in distributed systems using Sagas" section, page 176 in PDF (this is not a duplicate)

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#39]
We will not dive into the implementation of Sagas in this chapter, but only provide a high level `overview what` they are and why they exist.

Suggestion for grammar correction:
We will not dive into the implementation of Sagas in this chapter, but only provide a high level `overview of what` they are and why they exist.

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
