### ISSUE TITLE
Grammar suggestion in "Handling transactions in distributed systems using Sagas" section, page 176-177 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#40]
We will talk about the implementation in Part II of the book, where you will learn`,` that I personally don ́t use Sagas `typically` at all.

Suggestion for grammar:
We will talk about the implementation in Part II of the book, where you will learn that I personally don ́t `typically` use Sagas at all.

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
