### ISSUE TITLE
Grammar suggestion in "Handling transactions in distributed systems using Sagas" section, page 177 in PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#41]
Make your decisions on a case by case basis and make sure`,` you don ́t make things more complicated than they have to be.

Suggestion for grammar (misplaced comma):
Make your decisions on a case by case basis`,` and make sure you don ́t make things more complicated than they have to be.

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
