### ISSUE TITLE
Grammar suggestion in the "Vertical Slicing" section, page 183 of PDF

### ISSUE THREAD

**Issue by gimelg** [dilgerma/eventsourcing-book#43]
There are many ways to define coupling `and there are a lot of words, nobody can remember` (afferent coupling , efferent coupling are just 2 examples - feel free to look them up).

Suggestion for grammar and readability:
There are many ways to define coupling`, and there are many words used to describe it – most of which no one can remember (afferent coupling and efferent coupling are just 2 examples;` feel free to look them up).

*based on PDF version released Dec 2, 2024

**Comment by dilgerma** [comment]
thanks!
