### ISSUE TITLE
Link not provided

### ISSUE THREAD

**Issue by Chris-May** [dilgerma/eventsourcing-book#7]
In the "Understanding Eventsourcing" chapter, you mentioned how Adam Dymitruk recently built an event-sourced Open Space Management System using a file-based Event Store.

The end of the paragraph reads:
> You can follow the stream on Twitch.7

Footnote 7 is:
> You can follow the stream on Twitch.

I imagine it should either be a link to his Twitch account or deleted.

**Comment by dilgerma** [comment]
thanks, link added
