### ISSUE TITLE
Arrows point in wrong direction on Fig. 3.12

### ISSUE THREAD

**Issue by mackie-connell** [dilgerma/eventsourcing-book#9]
The left side of _Fig. 3.12 - Translation Pattern Variations_ has two arrows that appear to be pointing backwards.

1. The Inventory Changed event is incorrectly pointing to the Change Inventory command.
2. The Change Inventory command is incorrectly pointing to the automation gear.

**Comment by dilgerma** [comment]
thanks! fixed

**Comment by bpringe** [comment]
@dilgerma First of all thanks for writing this awesome book! I just came across this issue and I'm curious as to how quickly fixes make it into the artifact downloadable from Leanpub. I purchased the book there on 2024-12-02, and it seems this was fixed prior to that. I'm guessing the fix didn't make it to Leanpub before I downloaded it.

**Comment by dilgerma** [comment]
Hi, it should be in there and it was fixed a while ago.

![image](https://github.com/user-attachments/assets/c0b5a565-21be-4be9-9643-e4c3696217b0)

this is the correct image

**Comment by bpringe** [comment]
Thanks. I guess it just wasn't in there by the time I downloaded it.
